# Generated by Django 5.2.1 on 2025-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, default='media/default.jpg', max_length=255, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos'),
        ),
    ]
