# Generated by Django 5.2.1 on 2025-05-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_thumbnail_alter_movie_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='thumbnails/'),
        ),
    ]
