# Generated by Django 5.2.1 on 2025-05-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_thumbnail_alter_movie_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos'),
        ),
    ]
